version: '3.9'

services: 
  db:
    image: postgres:16
    container_name: blog_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_NAME=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'